[theme]
primaryColor = "#036380"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F8FA"
textColor = "#1E293B"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
